// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-sHlpFG8APrr6vgrl8tSZLR_PJB9gv9U',
    appId: '1:655954397704:web:47ffbdf57f8d3550e2dfbd',
    messagingSenderId: '655954397704',
    projectId: 'my-expences-proj',
    authDomain: 'my-expences-proj.firebaseapp.com',
    storageBucket: 'my-expences-proj.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACk_VvOey_FdhAoGaobYi9U_h4wJC9Xf0',
    appId: '1:655954397704:android:d4b3d4318cb44800e2dfbd',
    messagingSenderId: '655954397704',
    projectId: 'my-expences-proj',
    storageBucket: 'my-expences-proj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMjYX16Tv00SF7Kqe_5USrydloH8aWwKE',
    appId: '1:655954397704:ios:61670165ebba3941e2dfbd',
    messagingSenderId: '655954397704',
    projectId: 'my-expences-proj',
    storageBucket: 'my-expences-proj.firebasestorage.app',
    iosBundleId: 'com.example.expenceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMjYX16Tv00SF7Kqe_5USrydloH8aWwKE',
    appId: '1:655954397704:ios:61670165ebba3941e2dfbd',
    messagingSenderId: '655954397704',
    projectId: 'my-expences-proj',
    storageBucket: 'my-expences-proj.firebasestorage.app',
    iosBundleId: 'com.example.expenceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-sHlpFG8APrr6vgrl8tSZLR_PJB9gv9U',
    appId: '1:655954397704:web:6043f4af27045efde2dfbd',
    messagingSenderId: '655954397704',
    projectId: 'my-expences-proj',
    authDomain: 'my-expences-proj.firebaseapp.com',
    storageBucket: 'my-expences-proj.firebasestorage.app',
  );
}
